### ISSUE TITLE
Does not honour setReadOnly(true)

### ISSUE THREAD

**Issue by enver-haase** [vaadin/vaadin-date-time-picker-flow#54]
Looks the same and I can edit the value visually.

**Comment by tomivirkki** [comment]
```java
DateTimePicker dtp = new DateTimePicker("Date-time-picker");
dtp.setReadOnly(true);
add(dtp);
```
Works fine for me:

<img width="412" alt="Screenshot 2020-06-23 13 56 57" src="https://user-images.githubusercontent.com/1222264/85395925-8cf7fa80-b559-11ea-9a65-586b2f70cdbd.png">
